import = [
  # "~/.dots/vendor/alacritty-theme/themes/everforest_light.toml"
  "~/.dots/vendor/alacritty-theme/themes/ayu_light.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 15
# size = 20

[font.bold]
family = "Fira Code"
style = "Retina"

[font.bold_italic]
family = "Fira Code"
style = "Retina"

[font.italic]
family = "Fira Code"
style = "Retina"

[font.normal]
family = "Fira Code"
style = "Retina"

[scrolling]
history = 0

[shell]
program = "zsh"

[window]
option_as_alt = "Both"
startup_mode = "Fullscreen"

[window.padding]
x = 1
y = 1
